Update build Docker model section

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,10 +39,21 @@ jobs:
           mlflow run MLProject --env-manager=local
 
       - name: Get latest MLflow run_id
+        id: get_run_id
         run: |
-          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
-          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
-          echo "Latest run_id: $RUN_ID"
+          export MLFLOW_TRACKING_URI=file:./mlruns
+
+          experiment_id=0
+          echo "experiment_id=$experiment_id" >> $GITHUB_ENV
+
+          run_id=$(ls -1t "./mlruns/$experiment_id" | grep -E '^[a-f0-9]{32}$' | head -n 1)
+          if [ -z "$run_id" ]; then
+            echo "Failed to get run_id"
+            exit 1
+          fi
+
+          echo "Latest run_id: $run_id"
+          echo "MLFLOW_RUN_ID=$run_id" >> $GITHUB_ENV
 
       - name: Upload to GitHub
         run: |
@@ -56,7 +67,7 @@ jobs:
 
       - name: Build Docker Model
         run: |
-          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "diabetes-prediction"
+          mlflow models build-docker -m "runs:/${{ env.MLFLOW_RUN_ID }}/model" -n "diabetes-prediction"
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
